"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-03 21:43:38.058885
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_entity', sa.String(length=60), nullable=True),
    sa.Column('result_id', sa.BigInteger(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', name='uq_integration_event')
    )
    op.create_table('integrations',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('verification', sa.String(length=30), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.CheckConstraint("status IN ('connected', 'disconnected', 'degraded')", name='ck_integration_status'),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_limit_hits',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('bucket', sa.String(length=200), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limit_hits_at'), 'rate_limit_hits', ['at'], unique=False)
    op.create_index(op.f('ix_rate_limit_hits_bucket'), 'rate_limit_hits', ['bucket'], unique=False)
    op.create_table('routines',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('local_time', sa.String(length=5), nullable=False),
    sa.Column('weekdays', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('uses_model', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_result', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('usage_records',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_at'), 'usage_records', ['at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('telegram_user_id', sa.String(length=40), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'office', 'foreman', 'crew', 'agent', 'viewer')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('api_tokens',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('approvals',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('action_type', sa.String(length=60), nullable=False),
    sa.Column('target_type', sa.String(length=60), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('target_revision', sa.String(length=80), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('destination', sa.String(length=300), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_by_id', sa.BigInteger(), nullable=False),
    sa.Column('requested_via', sa.String(length=40), nullable=False),
    sa.Column('conversation_key', sa.String(length=120), nullable=True),
    sa.Column('decided_by_id', sa.BigInteger(), nullable=True),
    sa.Column('decided_via', sa.String(length=40), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected', 'expired', 'invalidated', 'executing', 'executed', 'failed', 'cancelled')", name='ck_approval_status'),
    sa.CheckConstraint("status NOT IN ('approved','rejected','executing','executed','failed') OR decided_by_id IS NOT NULL", name='ck_approval_decider'),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_conversation_key'), 'approvals', ['conversation_key'], unique=False)
    op.create_index('ix_approvals_status', 'approvals', ['status'], unique=False)
    op.create_table('assemblies',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('trade', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_example', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_role', sa.String(length=20), nullable=True),
    sa.Column('via', sa.String(length=40), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_at'), 'audit_events', ['at'], unique=False)
    op.create_table('contacts',
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('phone_normalized', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('email_normalized', sa.String(length=254), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('trade', sa.String(length=80), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('merged_into_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("kind IN ('customer', 'vendor', 'subcontractor', 'inspector', 'other')", name='ck_contacts_kind'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['merged_into_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_email_normalized'), 'contacts', ['email_normalized'], unique=False)
    op.create_index(op.f('ix_contacts_phone_normalized'), 'contacts', ['phone_normalized'], unique=False)
    op.create_table('crew_members',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('trade', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('daily_capacity_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_proposals',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('proposal', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_by_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("status IN ('proposed', 'accepted', 'rejected')", name='ck_learn_status'),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('web_sessions',
    sa.Column('id_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_hash')
    )
    op.create_table('outbox_jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('external_effect', sa.Boolean(), nullable=False),
    sa.Column('approval_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lease_owner', sa.String(length=80), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('provider_ref', sa.String(length=200), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'leased', 'succeeded', 'failed', 'dead', 'unknown', 'blocked', 'simulated')", name='ck_outbox_status'),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_outbox_ready', 'outbox_jobs', ['status', 'next_attempt_at'], unique=False)
    op.create_table('rates',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=False),
    sa.Column('source_date', sa.Date(), nullable=False),
    sa.Column('geography', sa.String(length=120), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('vendor_contact_id', sa.BigInteger(), nullable=True),
    sa.Column('supersedes_id', sa.BigInteger(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("category IN ('material', 'labor', 'equipment', 'subcontract', 'delivery', 'disposal', 'other')", name='ck_rates_category'),
    sa.CheckConstraint("status IN ('verified', 'owner_entered', 'provisional', 'expired')", name='ck_rates_status'),
    sa.CheckConstraint('unit_cost >= 0', name='ck_rates_nonneg'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['rates.id'], ),
    sa.ForeignKeyConstraint(['vendor_contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rates_code_active', 'rates', ['code', 'active'], unique=False)
    op.create_table('sites',
    sa.Column('contact_id', sa.BigInteger(), nullable=True),
    sa.Column('address_line', sa.String(length=300), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('address_normalized', sa.String(length=300), nullable=False),
    sa.Column('jurisdiction', sa.String(length=120), nullable=True),
    sa.Column('jurisdiction_status', sa.String(length=20), nullable=False),
    sa.Column('access_notes', sa.Text(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_address_normalized'), 'sites', ['address_normalized'], unique=False)
    op.create_table('leads',
    sa.Column('contact_id', sa.BigInteger(), nullable=False),
    sa.Column('site_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('job_type', sa.String(length=80), nullable=True),
    sa.Column('scope_text', sa.Text(), nullable=True),
    sa.Column('timing_text', sa.String(length=300), nullable=True),
    sa.Column('budget_text', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('source_ref', sa.String(length=200), nullable=True),
    sa.Column('next_action', sa.String(length=300), nullable=True),
    sa.Column('next_action_due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extraction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('possible_duplicate_of_id', sa.BigInteger(), nullable=True),
    sa.Column('lost_reason', sa.String(length=300), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("status IN ('inquiry', 'qualified', 'site_visit', 'estimating', 'proposal', 'follow_up', 'won', 'lost')", name='ck_leads_status'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['possible_duplicate_of_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('job_id', sa.BigInteger(), nullable=True),
    sa.Column('lead_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=200), nullable=False),
    sa.Column('revision_of_id', sa.BigInteger(), nullable=True),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.String(length=300), nullable=True),
    sa.Column('pages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(title,'') || ' ' || coalesce(text_content,''))", persisted=True), nullable=True),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("status IN ('stored', 'quarantined', 'rejected')", name='ck_doc_status'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name='fk_documents_job', use_alter=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['revision_of_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_fts', 'documents', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_documents_job_id'), 'documents', ['job_id'], unique=False)
    op.create_index(op.f('ix_documents_lead_id'), 'documents', ['lead_id'], unique=False)
    op.create_index(op.f('ix_documents_sha256'), 'documents', ['sha256'], unique=False)
    op.create_table('estimates',
    sa.Column('lead_id', sa.BigInteger(), nullable=True),
    sa.Column('job_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('pricing_mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("pricing_mode IN ('labor_only', 'turnkey')", name='ck_est_mode'),
    sa.CheckConstraint("status IN ('draft', 'proposed', 'accepted', 'declined', 'superseded', 'void')", name='ck_est_status'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name='fk_estimates_job', use_alter=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('site_id', sa.BigInteger(), nullable=True),
    sa.Column('lead_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_proposal_id', sa.BigInteger(), nullable=True),
    sa.Column('source_estimate_revision_id', sa.BigInteger(), nullable=True),
    sa.Column('contract_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('retainage_pct', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('planned_start', sa.Date(), nullable=True),
    sa.Column('planned_finish', sa.Date(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("status IN ('planned', 'active', 'on_hold', 'complete', 'closed', 'cancelled')", name='ck_job_status'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['source_estimate_revision_id'], ['estimate_revisions.id'], name='fk_jobs_est_rev', use_alter=True),
    sa.ForeignKeyConstraint(['source_proposal_id'], ['proposals.id'], name='fk_jobs_proposal', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_proposal_id')
    )
    op.create_table('lead_transitions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('lead_id', sa.BigInteger(), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_transitions_lead_id'), 'lead_transitions', ['lead_id'], unique=False)
    op.create_table('appointments',
    sa.Column('lead_id', sa.BigInteger(), nullable=True),
    sa.Column('job_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confirmation_evidence', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("status <> 'confirmed' OR confirmation_evidence IS NOT NULL", name='ck_appt_confirm_evidence'),
    sa.CheckConstraint("status IN ('tentative', 'confirmed', 'cancelled', 'completed')", name='ck_appt_status'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change_orders',
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('cost_code', sa.String(length=40), nullable=True),
    sa.Column('schedule_impact_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('evidence_document_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('customer_approval_evidence', sa.String(length=500), nullable=True),
    sa.Column('customer_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supersedes_id', sa.BigInteger(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("status <> 'customer_approved' OR customer_approval_evidence IS NOT NULL", name='ck_co_evidence'),
    sa.CheckConstraint("status IN ('draft', 'pending_approval', 'approved_to_issue', 'issued', 'customer_approved', 'rejected', 'void')", name='ck_co_status'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['change_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'number', 'revision_no', name='uq_co_number_rev')
    )
    op.create_index(op.f('ix_change_orders_job_id'), 'change_orders', ['job_id'], unique=False)
    op.create_table('daily_logs',
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('original_note', sa.Text(), nullable=False),
    sa.Column('extraction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('work_completed', sa.Text(), nullable=True),
    sa.Column('labor', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('materials', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('delays', sa.Text(), nullable=True),
    sa.Column('issues', sa.Text(), nullable=True),
    sa.Column('tomorrow_plan', sa.Text(), nullable=True),
    sa.Column('photo_document_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'final')", name='ck_dlog_status'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_logs_job_id'), 'daily_logs', ['job_id'], unique=False)
    op.create_table('estimate_revisions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('estimate_id', sa.BigInteger(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('quote_type', sa.String(length=20), nullable=False),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('contingency_pct', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('overhead_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('profit_method', sa.String(length=10), nullable=False),
    sa.Column('profit_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('material_tax_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('sales_tax_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('tax_mode', sa.String(length=30), nullable=False),
    sa.Column('labor_burden_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('scope_summary', sa.Text(), nullable=True),
    sa.Column('inclusions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exclusions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unresolved_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('totals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("profit_method <> 'margin' OR profit_pct IS NULL OR (profit_pct >= 0 AND profit_pct < 1)", name='ck_rev_margin_range'),
    sa.CheckConstraint("profit_method IN ('markup', 'margin')", name='ck_rev_profit_method'),
    sa.CheckConstraint("quote_type IN ('rough_range', 'firm')", name='ck_rev_quote_type'),
    sa.CheckConstraint("status IN ('draft', 'locked', 'superseded')", name='ck_rev_status'),
    sa.CheckConstraint('discount_amount >= 0 AND discount_pct >= 0 AND discount_pct < 1', name='ck_rev_discount'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estimate_id', 'revision_no', name='uq_est_rev')
    )
    op.create_index(op.f('ix_estimate_revisions_estimate_id'), 'estimate_revisions', ['estimate_id'], unique=False)
    op.create_table('job_assignments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'user_id', name='uq_job_assignment')
    )
    op.create_index(op.f('ix_job_assignments_job_id'), 'job_assignments', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_assignments_user_id'), 'job_assignments', ['user_id'], unique=False)
    op.create_table('job_budget_lines',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('cost_code', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('forecast_to_complete', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('forecast_note', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_budget_lines_job_id'), 'job_budget_lines', ['job_id'], unique=False)
    op.create_table('permits',
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=120), nullable=True),
    sa.Column('permit_type', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('application_ref', sa.String(length=120), nullable=True),
    sa.Column('submitted_on', sa.Date(), nullable=True),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('status_source', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("status IN ('not_determined', 'not_required_verified', 'required', 'applied', 'issued', 'expired', 'closed')", name='ck_permit_status'),
    sa.CheckConstraint("status NOT IN ('issued','not_required_verified') OR status_source IS NOT NULL", name='ck_permit_source'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permits_job_id'), 'permits', ['job_id'], unique=False)
    op.create_table('punch_items',
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('evidence_document_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("status IN ('open', 'done', 'verified')", name='ck_punch_status'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_punch_items_job_id'), 'punch_items', ['job_id'], unique=False)
    op.create_table('rfis',
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('directed_to', sa.String(length=200), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'number', name='uq_rfi_number')
    )
    op.create_index(op.f('ix_rfis_job_id'), 'rfis', ['job_id'], unique=False)
    op.create_table('vendor_documents',
    sa.Column('contact_id', sa.BigInteger(), nullable=False),
    sa.Column('doc_type', sa.String(length=40), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=True),
    sa.Column('identifier', sa.String(length=120), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('verification_note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("verification_status IN ('unverified', 'owner_reviewed', 'verified_with_issuer')", name='ck_vdoc_verif'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_documents_contact_id'), 'vendor_documents', ['contact_id'], unique=False)
    op.create_table('vendor_quotes',
    sa.Column('vendor_id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('received_on', sa.Date(), nullable=False),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('lines', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('delivery_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_assumption', sa.String(length=120), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('availability', sa.String(length=200), nullable=True),
    sa.Column('document_id', sa.BigInteger(), nullable=True),
    sa.Column('is_subcontract', sa.Boolean(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estimate_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('revision_id', sa.BigInteger(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('cost_code', sa.String(length=40), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('quantity_source', sa.String(length=200), nullable=True),
    sa.Column('waste_pct', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('rate_id', sa.BigInteger(), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('rate_status', sa.String(length=20), nullable=True),
    sa.Column('rate_source', sa.String(length=300), nullable=True),
    sa.Column('rate_source_date', sa.Date(), nullable=True),
    sa.Column('taxable', sa.Boolean(), nullable=False),
    sa.Column('customer_visible_text', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("kind IN ('material', 'labor', 'subcontract', 'equipment', 'delivery', 'disposal', 'allowance', 'other')", name='ck_item_kind'),
    sa.CheckConstraint('quantity IS NULL OR quantity >= 0', name='ck_item_qty'),
    sa.CheckConstraint('waste_pct >= 0 AND waste_pct < 1', name='ck_item_waste'),
    sa.ForeignKeyConstraint(['rate_id'], ['rates.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['estimate_revisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estimate_items_revision_id'), 'estimate_items', ['revision_id'], unique=False)
    op.create_table('inspections',
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('permit_id', sa.BigInteger(), nullable=True),
    sa.Column('inspection_type', sa.String(length=80), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('result_source', sa.String(length=500), nullable=True),
    sa.Column('deficiencies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("result IN ('not_scheduled', 'scheduled', 'unverified', 'passed', 'failed', 'partial')", name='ck_insp_result'),
    sa.CheckConstraint("result NOT IN ('passed','failed','partial') OR result_source IS NOT NULL", name='ck_insp_source'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['permit_id'], ['permits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_job_id'), 'inspections', ['job_id'], unique=False)
    op.create_table('invoices',
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('milestone_key', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('lines', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('retainage_pct', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('retainage_held', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_due', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('external_system', sa.String(length=40), nullable=True),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('change_order_id', sa.BigInteger(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'pending_approval', 'approved', 'issued', 'partially_paid', 'paid', 'void')", name='ck_inv_status'),
    sa.ForeignKeyConstraint(['change_order_id'], ['change_orders.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_system', 'external_id', name='uq_inv_external'),
    sa.UniqueConstraint('job_id', 'milestone_key', name='uq_inv_milestone'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_invoices_job_id'), 'invoices', ['job_id'], unique=False)
    op.create_table('proposals',
    sa.Column('estimate_id', sa.BigInteger(), nullable=False),
    sa.Column('estimate_revision_id', sa.BigInteger(), nullable=False),
    sa.Column('proposal_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('pdf_document_id', sa.BigInteger(), nullable=True),
    sa.Column('approval_id', sa.BigInteger(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acceptance_evidence', sa.String(length=500), nullable=True),
    sa.Column('acceptance_document_id', sa.BigInteger(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("status <> 'accepted' OR acceptance_evidence IS NOT NULL", name='ck_proposal_accept_evidence'),
    sa.CheckConstraint("status IN ('draft', 'pending_approval', 'approved', 'issued', 'accepted', 'declined', 'superseded', 'void')", name='ck_proposal_status'),
    sa.ForeignKeyConstraint(['acceptance_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimates.id'], ),
    sa.ForeignKeyConstraint(['estimate_revision_id'], ['estimate_revisions.id'], ),
    sa.ForeignKeyConstraint(['pdf_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estimate_id', 'proposal_no', name='uq_proposal_no')
    )
    op.create_index(op.f('ix_proposals_estimate_id'), 'proposals', ['estimate_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('vendor_id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('vendor_quote_id', sa.BigInteger(), nullable=True),
    sa.Column('needed_by', sa.Date(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('delivery_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'pending_approval', 'approved', 'issued', 'partially_received', 'received', 'cancelled')", name='ck_po_status'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['vendor_quote_id'], ['vendor_quotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_purchase_orders_job_id'), 'purchase_orders', ['job_id'], unique=False)
    op.create_table('research_sources',
    sa.Column('job_id', sa.BigInteger(), nullable=True),
    sa.Column('permit_id', sa.BigInteger(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edition', sa.String(length=120), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('passage', sa.Text(), nullable=True),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['permit_id'], ['permits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_entries',
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('cost_code', sa.String(length=40), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('vendor_id', sa.BigInteger(), nullable=True),
    sa.Column('vendor_name', sa.String(length=200), nullable=True),
    sa.Column('po_id', sa.BigInteger(), nullable=True),
    sa.Column('document_id', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('match_note', sa.String(length=300), nullable=True),
    sa.Column('corrects_id', sa.BigInteger(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("kind IN ('labor', 'material', 'subcontract', 'equipment', 'other')", name='ck_cost_kind'),
    sa.CheckConstraint("status IN ('unreviewed', 'approved', 'needs_review', 'reversed')", name='ck_cost_status'),
    sa.ForeignKeyConstraint(['corrects_id'], ['cost_entries.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_cost_external')
    )
    op.create_index(op.f('ix_cost_entries_job_id'), 'cost_entries', ['job_id'], unique=False)
    op.create_table('payments',
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('invoice_id', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('received_on', sa.Date(), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('verification_source', sa.String(length=300), nullable=True),
    sa.Column('applies_to_retainage', sa.Boolean(), nullable=False),
    sa.Column('external_system', sa.String(length=40), nullable=True),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("status = 'reported_unverified' OR verification_source IS NOT NULL", name='ck_pay_verified_source'),
    sa.CheckConstraint("status IN ('reported_unverified', 'verified', 'reconciled', 'reversed')", name='ck_pay_status'),
    sa.CheckConstraint('amount > 0', name='ck_pay_positive'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_system', 'external_id', name='uq_pay_external')
    )
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_job_id'), 'payments', ['job_id'], unique=False)
    op.create_table('po_lines',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('po_id', sa.BigInteger(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('cost_code', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_po_lines_po_id'), 'po_lines', ['po_id'], unique=False)
    op.create_table('tasks',
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('phase', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('weather_sensitive', sa.Boolean(), nullable=False),
    sa.Column('requires_permit_id', sa.BigInteger(), nullable=True),
    sa.Column('requires_inspection_id', sa.BigInteger(), nullable=True),
    sa.Column('requires_po_id', sa.BigInteger(), nullable=True),
    sa.Column('responsible_user_id', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("status IN ('todo', 'scheduled', 'in_progress', 'blocked', 'done', 'cancelled')", name='ck_task_status'),
    sa.CheckConstraint('ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at', name='ck_task_times'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['requires_inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['requires_permit_id'], ['permits.id'], ),
    sa.ForeignKeyConstraint(['requires_po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_job_id'), 'tasks', ['job_id'], unique=False)
    op.create_table('task_assignments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('crew_member_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['crew_member_id'], ['crew_members.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'crew_member_id', name='uq_task_assign')
    )
    op.create_index(op.f('ix_task_assignments_crew_member_id'), 'task_assignments', ['crew_member_id'], unique=False)
    op.create_index(op.f('ix_task_assignments_task_id'), 'task_assignments', ['task_id'], unique=False)
    op.create_table('task_dependencies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('depends_on_task_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('task_id <> depends_on_task_id', name='ck_task_dep_self'),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'depends_on_task_id', name='uq_task_dep')
    )
    op.create_index(op.f('ix_task_dependencies_task_id'), 'task_dependencies', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_dependencies_task_id'), table_name='task_dependencies')
    op.drop_table('task_dependencies')
    op.drop_index(op.f('ix_task_assignments_task_id'), table_name='task_assignments')
    op.drop_index(op.f('ix_task_assignments_crew_member_id'), table_name='task_assignments')
    op.drop_table('task_assignments')
    op.drop_index(op.f('ix_tasks_job_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_po_lines_po_id'), table_name='po_lines')
    op.drop_table('po_lines')
    op.drop_index(op.f('ix_payments_job_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_cost_entries_job_id'), table_name='cost_entries')
    op.drop_table('cost_entries')
    op.drop_table('research_sources')
    op.drop_index(op.f('ix_purchase_orders_job_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_proposals_estimate_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index(op.f('ix_invoices_job_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_inspections_job_id'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_estimate_items_revision_id'), table_name='estimate_items')
    op.drop_table('estimate_items')
    op.drop_table('vendor_quotes')
    op.drop_index(op.f('ix_vendor_documents_contact_id'), table_name='vendor_documents')
    op.drop_table('vendor_documents')
    op.drop_index(op.f('ix_rfis_job_id'), table_name='rfis')
    op.drop_table('rfis')
    op.drop_index(op.f('ix_punch_items_job_id'), table_name='punch_items')
    op.drop_table('punch_items')
    op.drop_index(op.f('ix_permits_job_id'), table_name='permits')
    op.drop_table('permits')
    op.drop_index(op.f('ix_job_budget_lines_job_id'), table_name='job_budget_lines')
    op.drop_table('job_budget_lines')
    op.drop_index(op.f('ix_job_assignments_user_id'), table_name='job_assignments')
    op.drop_index(op.f('ix_job_assignments_job_id'), table_name='job_assignments')
    op.drop_table('job_assignments')
    op.drop_index(op.f('ix_estimate_revisions_estimate_id'), table_name='estimate_revisions')
    op.drop_table('estimate_revisions')
    op.drop_index(op.f('ix_daily_logs_job_id'), table_name='daily_logs')
    op.drop_table('daily_logs')
    op.drop_index(op.f('ix_change_orders_job_id'), table_name='change_orders')
    op.drop_table('change_orders')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_lead_transitions_lead_id'), table_name='lead_transitions')
    op.drop_table('lead_transitions')
    op.drop_table('jobs')
    op.drop_table('estimates')
    op.drop_index(op.f('ix_documents_sha256'), table_name='documents')
    op.drop_index(op.f('ix_documents_lead_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_job_id'), table_name='documents')
    op.drop_index('ix_documents_fts', table_name='documents', postgresql_using='gin')
    op.drop_table('documents')
    op.drop_table('leads')
    op.drop_index(op.f('ix_sites_address_normalized'), table_name='sites')
    op.drop_table('sites')
    op.drop_index('ix_rates_code_active', table_name='rates')
    op.drop_table('rates')
    op.drop_index('ix_outbox_ready', table_name='outbox_jobs')
    op.drop_table('outbox_jobs')
    op.drop_table('web_sessions')
    op.drop_table('org_settings')
    op.drop_table('learning_proposals')
    op.drop_table('crew_members')
    op.drop_index(op.f('ix_contacts_phone_normalized'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email_normalized'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_audit_events_at'), table_name='audit_events')
    op.drop_index('ix_audit_entity', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('assemblies')
    op.drop_index('ix_approvals_status', table_name='approvals')
    op.drop_index(op.f('ix_approvals_conversation_key'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_table('api_tokens')
    op.drop_table('users')
    op.drop_index(op.f('ix_usage_records_at'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_table('routines')
    op.drop_index(op.f('ix_rate_limit_hits_bucket'), table_name='rate_limit_hits')
    op.drop_index(op.f('ix_rate_limit_hits_at'), table_name='rate_limit_hits')
    op.drop_table('rate_limit_hits')
    op.drop_table('notifications')
    op.drop_table('integrations')
    op.drop_table('integration_events')
    # ### end Alembic commands ###
